const axios = require('axios');

/**
 * Ekart (Ecom Express) Integration Service
 * 
 * This service handles all interactions with Ekart API for:
 * - Creating shipments
 * - Tracking shipments
 * - Calculating shipping rates
 * - Scheduling pickups
 * - Generating AWB (Air Waybill) numbers
 */

class EkartService {
    constructor() {
        // Ekart API credentials (store in .env file)
        this.apiUrl = process.env.EKART_API_URL || 'https://api.ecomexpress.in';
        this.username = process.env.EKART_USERNAME;
        this.password = process.env.EKART_PASSWORD;
        this.apiKey = process.env.EKART_API_KEY;

        // Your business details
        this.pickupLocation = {
            name: process.env.BUSINESS_NAME || 'Vedessa',
            address: process.env.PICKUP_ADDRESS || '',
            city: process.env.PICKUP_CITY || '',
            state: process.env.PICKUP_STATE || '',
            pincode: process.env.PICKUP_PINCODE || '',
            phone: process.env.PICKUP_PHONE || '',
            email: process.env.PICKUP_EMAIL || ''
        };
    }

    /**
     * Create a new shipment with Ekart
     * @param {Object} orderData - Order details
     * @returns {Promise<Object>} Shipment details with AWB number
     */
    async createShipment(orderData) {
        try {
            const {
                orderId,
                customerName,
                customerPhone,
                customerEmail,
                shippingAddress,
                items,
                totalAmount,
                paymentMethod,
                weight = 0.5, // Default weight in kg
                dimensions = { length: 10, width: 10, height: 10 } // in cm
            } = orderData;

            const shipmentData = {
                AWB_NUMBER: '', // Will be auto-generated by Ekart
                ORDER_NUMBER: orderId,
                PRODUCT: 'PPD', // PPD = Prepaid, COD = Cash on Delivery
                CONSIGNEE: customerName,
                CONSIGNEE_ADDRESS1: shippingAddress.address,
                CONSIGNEE_ADDRESS2: shippingAddress.landmark || '',
                CONSIGNEE_ADDRESS3: '',
                DESTINATION_CITY: shippingAddress.city,
                PINCODE: shippingAddress.pincode,
                STATE: shippingAddress.state,
                MOBILE: customerPhone,
                TELEPHONE: customerPhone,
                ITEM_DESCRIPTION: items.map(item => item.name).join(', '),
                PIECES: items.length,
                COLLECTABLE_VALUE: paymentMethod === 'COD' ? totalAmount : 0,
                DECLARED_VALUE: totalAmount,
                ACTUAL_WEIGHT: weight,
                VOLUMETRIC_WEIGHT: this.calculateVolumetricWeight(dimensions),
                LENGTH: dimensions.length,
                BREADTH: dimensions.width,
                HEIGHT: dimensions.height,
                PICKUP_NAME: this.pickupLocation.name,
                PICKUP_ADDRESS_LINE1: this.pickupLocation.address,
                PICKUP_ADDRESS_LINE2: '',
                PICKUP_PINCODE: this.pickupLocation.pincode,
                PICKUP_PHONE: this.pickupLocation.phone,
                PICKUP_MOBILE: this.pickupLocation.phone,
                RETURN_NAME: this.pickupLocation.name,
                RETURN_ADDRESS_LINE1: this.pickupLocation.address,
                RETURN_ADDRESS_LINE2: '',
                RETURN_PINCODE: this.pickupLocation.pincode,
                RETURN_PHONE: this.pickupLocation.phone,
                RETURN_MOBILE: this.pickupLocation.phone
            };

            // In production, make actual API call
            if (this.apiKey && this.username) {
                const response = await axios.post(
                    `${this.apiUrl}/apiv2/manifest_awb/`,
                    shipmentData,
                    {
                        headers: {
                            'Content-Type': 'application/json',
                            'username': this.username,
                            'password': this.password
                        }
                    }
                );

                return {
                    success: true,
                    awbNumber: response.data.awb,
                    trackingUrl: `https://ecomexpress.in/tracking/?awb_no=${response.data.awb}`,
                    shipmentId: response.data.shipment_id,
                    estimatedDelivery: response.data.estimated_delivery
                };
            }

            // Mock response for development
            const mockAwb = `EKART${Date.now()}${Math.floor(Math.random() * 1000)}`;
            return {
                success: true,
                awbNumber: mockAwb,
                trackingUrl: `https://ecomexpress.in/tracking/?awb_no=${mockAwb}`,
                shipmentId: `SHIP${Date.now()}`,
                estimatedDelivery: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
                mock: true
            };

        } catch (error) {
            console.error('Ekart shipment creation error:', error);
            throw new Error(error.response?.data?.message || 'Failed to create shipment');
        }
    }

    /**
     * Track a shipment
     * @param {string} awbNumber - AWB tracking number
     * @returns {Promise<Object>} Tracking details
     */
    async trackShipment(awbNumber) {
        try {
            // In production, make actual API call
            if (this.apiKey && this.username) {
                const response = await axios.get(
                    `${this.apiUrl}/track_me/api/mawbd/`,
                    {
                        params: { awb: awbNumber },
                        headers: {
                            'username': this.username,
                            'password': this.password
                        }
                    }
                );

                return {
                    success: true,
                    status: response.data.status,
                    location: response.data.location,
                    updates: response.data.scans,
                    estimatedDelivery: response.data.expected_delivery_date
                };
            }

            // Mock response for development
            return {
                success: true,
                status: 'In Transit',
                location: 'Mumbai Hub',
                updates: [
                    {
                        timestamp: new Date().toISOString(),
                        status: 'Picked Up',
                        location: this.pickupLocation.city,
                        description: 'Shipment picked up from origin'
                    },
                    {
                        timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
                        status: 'In Transit',
                        location: 'Mumbai Hub',
                        description: 'Shipment in transit'
                    }
                ],
                estimatedDelivery: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
                mock: true
            };

        } catch (error) {
            console.error('Ekart tracking error:', error);
            throw new Error('Failed to track shipment');
        }
    }

    /**
     * Calculate shipping rate
     * @param {Object} params - Shipping parameters
     * @returns {Promise<Object>} Shipping rate details
     */
    async calculateShippingRate(params) {
        try {
            const {
                originPincode = this.pickupLocation.pincode,
                destinationPincode,
                weight = 0.5,
                paymentMethod = 'PREPAID'
            } = params;

            // In production, make actual API call
            if (this.apiKey && this.username) {
                const response = await axios.post(
                    `${this.apiUrl}/rate_calculator/`,
                    {
                        origin_pincode: originPincode,
                        destination_pincode: destinationPincode,
                        weight: weight,
                        payment_mode: paymentMethod
                    },
                    {
                        headers: {
                            'username': this.username,
                            'password': this.password
                        }
                    }
                );

                return {
                    success: true,
                    rate: response.data.rate,
                    estimatedDays: response.data.estimated_days
                };
            }

            // Mock rate calculation for development
            const baseRate = 50;
            const perKgRate = 30;
            const codCharge = paymentMethod === 'COD' ? 50 : 0;
            const totalRate = baseRate + (weight * perKgRate) + codCharge;

            return {
                success: true,
                rate: totalRate,
                estimatedDays: 5,
                breakdown: {
                    baseRate,
                    weightCharge: weight * perKgRate,
                    codCharge,
                    total: totalRate
                },
                mock: true
            };

        } catch (error) {
            console.error('Ekart rate calculation error:', error);
            throw new Error('Failed to calculate shipping rate');
        }
    }

    /**
     * Schedule a pickup
     * @param {Object} pickupData - Pickup details
     * @returns {Promise<Object>} Pickup confirmation
     */
    async schedulePickup(pickupData) {
        try {
            const {
                pickupDate,
                awbNumbers = [],
                numberOfPieces = 1
            } = pickupData;

            // In production, make actual API call
            if (this.apiKey && this.username) {
                const response = await axios.post(
                    `${this.apiUrl}/pickup_request/`,
                    {
                        pickup_date: pickupDate,
                        awb_numbers: awbNumbers.join(','),
                        pieces: numberOfPieces,
                        pickup_address: this.pickupLocation.address,
                        pickup_pincode: this.pickupLocation.pincode,
                        pickup_phone: this.pickupLocation.phone
                    },
                    {
                        headers: {
                            'username': this.username,
                            'password': this.password
                        }
                    }
                );

                return {
                    success: true,
                    pickupId: response.data.pickup_id,
                    message: 'Pickup scheduled successfully'
                };
            }

            // Mock response for development
            return {
                success: true,
                pickupId: `PICKUP${Date.now()}`,
                message: 'Pickup scheduled successfully (Mock)',
                mock: true
            };

        } catch (error) {
            console.error('Ekart pickup scheduling error:', error);
            throw new Error('Failed to schedule pickup');
        }
    }

    /**
     * Cancel a shipment
     * @param {string} awbNumber - AWB number to cancel
     * @returns {Promise<Object>} Cancellation confirmation
     */
    async cancelShipment(awbNumber) {
        try {
            // In production, make actual API call
            if (this.apiKey && this.username) {
                const response = await axios.post(
                    `${this.apiUrl}/cancel_awb/`,
                    { awb_number: awbNumber },
                    {
                        headers: {
                            'username': this.username,
                            'password': this.password
                        }
                    }
                );

                return {
                    success: true,
                    message: 'Shipment cancelled successfully'
                };
            }

            // Mock response for development
            return {
                success: true,
                message: 'Shipment cancelled successfully (Mock)',
                mock: true
            };

        } catch (error) {
            console.error('Ekart shipment cancellation error:', error);
            throw new Error('Failed to cancel shipment');
        }
    }

    /**
     * Calculate volumetric weight
     * @param {Object} dimensions - Package dimensions
     * @returns {number} Volumetric weight in kg
     */
    calculateVolumetricWeight(dimensions) {
        const { length, width, height } = dimensions;
        // Volumetric weight = (L x W x H) / 5000
        return (length * width * height) / 5000;
    }

    /**
     * Generate shipping label (PDF)
     * @param {string} awbNumber - AWB number
     * @returns {Promise<Object>} Label URL
     */
    async generateShippingLabel(awbNumber) {
        try {
            // In production, make actual API call
            if (this.apiKey && this.username) {
                const response = await axios.get(
                    `${this.apiUrl}/apiv2/print_awb/`,
                    {
                        params: { awbs: awbNumber },
                        headers: {
                            'username': this.username,
                            'password': this.password
                        },
                        responseType: 'arraybuffer'
                    }
                );

                return {
                    success: true,
                    labelUrl: `data:application/pdf;base64,${Buffer.from(response.data).toString('base64')}`
                };
            }

            // Mock response for development
            return {
                success: true,
                labelUrl: `https://example.com/label/${awbNumber}.pdf`,
                mock: true
            };

        } catch (error) {
            console.error('Ekart label generation error:', error);
            throw new Error('Failed to generate shipping label');
        }
    }
}

module.exports = new EkartService();
